### ISSUE TITLE
Add 16 Routines to the Database

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#116]
Each of us will be adding at least 16 Routines to the RoutineDB so that we can flesh out the database.

**Comment by marknelsonengineer** [comment]
Good places for routines are:
http://www.grandillusions.com
http://www.theory11.com
http://www.penguinmagic.com
http://dananddave.com

**Comment by pkarjala** [comment]
In order to prevent duplication of work (IE, we put in the same routines), do we want to concentrate on a specific site each?  Or say, Mark focuses on Card Routines, David focuses on Scarf Routines, etc.?

**Comment by pkarjala** [comment]
Mark will add images in the 200 range, David in the 300 range, and Patrick in the 400 range.

**Comment by davidkneely** [comment]
Just finished adding my 16 routines. Going to run checkstyle and tests then I will be merging my branch with Milestone-1. #116

**Comment by marknelsonengineer** [comment]
My end is done.

**Comment by pkarjala** [comment]
All routines have been added for our pre-filled database!
