### ISSUE TITLE
What if a routine does not require any materials? Enter it in with no materials?

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#118]

**Comment by pkarjala** [comment]
I presume a Routine can be run with no Materials if it's a Mentalist type routine.  Will need to test if the site will allow for no-material Routines.

**Comment by marknelsonengineer** [comment]
Yea, there's lots of routines that don't need materials.  I've done tests and it works fine.  In fact, the View page says 'None'.
