### ISSUE TITLE
Add screenshots to the User Guide

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#131]

**Comment by davidkneely** [comment]
Adding images for wiki/User Guide to github issue to more easily host them here on github rather than on a separate server.

![screen shot 2015-04-20 at 8 25 45 am](https://cloud.githubusercontent.com/assets/10734935/7237472/5d10cb26-e737-11e4-9ba9-fde73b4e8672.png)

**Comment by pkarjala** [comment]
As per project guidelines from Dr. Johnson, all images should be hosted directly in the repo at /doc/images/.

See http://philipmjohnson.github.io/ics613s15/morea/project-management/reading-project-management-guidelines.html Item #3.

**Comment by davidkneely** [comment]
Adding image for User Creation - desktop.

![screen shot 2015-04-20 at 8 30 55 am](https://cloud.githubusercontent.com/assets/10734935/7237511/a88591cc-e737-11e4-8c01-f4261af2c4c9.png)

**Comment by davidkneely** [comment]
Adding Routine Creation - Desktop.

![screen shot 2015-04-20 at 8 33 07 am](https://cloud.githubusercontent.com/assets/10734935/7237544/ee66f852-e737-11e4-8dee-8de2ee646ad1.png)

**Comment by davidkneely** [comment]
Adding screenshot for Browsing Routines.

![screen shot 2015-04-20 at 8 35 01 am](https://cloud.githubusercontent.com/assets/10734935/7237590/3a49d122-e738-11e4-9134-5c379954859d.png)

**Comment by pkarjala** [comment]
I'd recommend creating a branch off of Master, placing all the necessary images into the doc/images/ folder, then committing that branch and merging back into Master.

**Comment by davidkneely** [comment]
Thanks for the recommendation Patrick. I'm right in the middle of finishing up with this process. Then I will loop back around to process your suggestion.

**Comment by pkarjala** [comment]
OK, great!  Please also see https://github.com/PlayWithMagic/PlayWithMagic.org/issues/131#issuecomment-94531876

**Comment by davidkneely** [comment]
Adding screenshot for Creating Sets.

![screen shot 2015-04-20 at 8 39 32 am](https://cloud.githubusercontent.com/assets/10734935/7237676/d3bc3368-e738-11e4-9c40-4e149efce1db.png)

**Comment by davidkneely** [comment]
Adding Browse Sets - Desktop Screenshot.

![screen shot 2015-04-20 at 8 35 13 am](https://cloud.githubusercontent.com/assets/10734935/7237724/148dbb00-e739-11e4-95df-8fe0dbdb98d1.png)

**Comment by davidkneely** [comment]
Adding Help - Desktop Screenshot.

![screen shot 2015-04-20 at 8 42 54 am](https://cloud.githubusercontent.com/assets/10734935/7237754/4be2b11e-e739-11e4-9eb3-e46c89087b4f.png)

**Comment by davidkneely** [comment]
Adding About - Desktop Screenshot.

![screen shot 2015-04-20 at 8 44 55 am](https://cloud.githubusercontent.com/assets/10734935/7237793/92de698c-e739-11e4-8287-e76b6070fa6f.png)

**Comment by davidkneely** [comment]
Adding mobile versions of desktop screenshots.

![image1](https://cloud.githubusercontent.com/assets/10734935/7238062/a286e0d8-e73b-11e4-811d-ef339d4fd408.png)
![image2](https://cloud.githubusercontent.com/assets/10734935/7238060/a285f358-e73b-11e4-8089-3c46b09d6c6c.png)
![image3](https://cloud.githubusercontent.com/assets/10734935/7238061/a2870018-e73b-11e4-9a7b-77d33bea426a.png)
![image4](https://cloud.githubusercontent.com/assets/10734935/7238064/a2879d0c-e73b-11e4-8927-788d7192e4c4.png)
![image5](https://cloud.githubusercontent.com/assets/10734935/7238065/a2879898-e73b-11e4-91ab-951bd697a3e0.png)
![image6](https://cloud.githubusercontent.com/assets/10734935/7238063/a28753f6-e73b-11e4-8ddb-86be1cc86a70.png)
![image7](https://cloud.githubusercontent.com/assets/10734935/7238066/a29e2f04-e73b-11e4-99a4-db6fd59f789e.png)
![image8](https://cloud.githubusercontent.com/assets/10734935/7238067/a29e967e-e73b-11e4-8c92-935186a97a60.png)

**Comment by davidkneely** [comment]
Looping back around to your comment now, Patrick. Creating a branch for uploading documentation images now.

**Comment by davidkneely** [comment]
Done. #131
