### ISSUE TITLE
Add links to theory11.com and dananddave.com where we pulled the routines from to populate the database.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#134]

**Comment by pkarjala** [comment]
Would likely fit best on the About page.

---

Patrick Karjala
pkarjala@gmail.com

**Comment by davidkneely** [comment]
Noting page to update with links to sites we pulled routines from: http://www.playwithmagic.org/about

**Comment by davidkneely** [comment]
Done. #134
