### ISSUE TITLE
Draft a Wiki page to show new project devs how to add a field to Routines

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#138]

**Comment by marknelsonengineer** [comment]
Done.  The only (minor) issue is that the images point into the Milestone-2 branch.  I think the Milestone-2 branch will be durable for awhile, so I don't feel an urgent need to merge w/ master and then fixup the links.

**Comment by pkarjala** [comment]
Yes, however, our documentation will expect to point to the Master branch when it's reviewed.  It may be safest to go ahead and do the merge and redirect the image pointers.

**Comment by marknelsonengineer** [comment]
Agreed.  Let’s do that on Tuesday.
