### ISSUE TITLE
Refactor the Readme.md file

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#139]
...per FP6 guidelines.

Review other GitHub landing pages (Readme.md) files for inspiration.

**Comment by pkarjala** [comment]
Have finished refactoring.  It's rather sparse, but it's supposed to be!  We'll spruce up the Wiki and the Home Page.

**Comment by marknelsonengineer** [comment]
Patrick... I'm not seeing the refactoring effort on GitHub.  Is it in a branch somewhere?

**Comment by marknelsonengineer** [comment]
https://github.com/PlayWithMagic/PlayWithMagic.org
... seems to have the old content.

**Comment by pkarjala** [comment]
All changes should be in the Milestone-2 branch at this time.  The changes are can be viewed here:  https://github.com/PlayWithMagic/PlayWithMagic.org/tree/Milestone-2

**Comment by marknelsonengineer** [comment]
I'm adding a screenshot

**Comment by marknelsonengineer** [comment]
1.  Add language about what makes the site unique.
2.  Consolidated the set of screenshots across the Project Home Page, User Guide and Readme.md file.
