### ISSUE TITLE
Rename the project to PlayWithMagic.org

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#140]

**Comment by marknelsonengineer** [comment]
Done.  

A few notes:
-  I considered adding the .org to the Organization's name as well.  I researched other projects, however, and nobody else is doing that.  So, for now, we'll stick with this.
-  I set a logo for the Organization... taking a square image of the book w/ stars.  
-  Notes about changing the repository name are here:
  https://help.github.com/articles/renaming-a-repository/

Highlights include:
When you rename a repository, all existing information is automatically redirected to the new name, including:
- Issues
- Wikis
- Stars
- Followers

In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:

`git remote set-url origin new_url`

**Comment by marknelsonengineer** [comment]
To mixup my repo, I:

Before the fix:

```
$ git remote -v
heroku  https://git.heroku.com/limitless-sands-9772.git (fetch)
heroku  https://git.heroku.com/limitless-sands-9772.git (push)
origin  https://github.com/PlayWithMagic/PlayWithMagic.git (fetch)
origin  https://github.com/PlayWithMagic/PlayWithMagic.git (push)
```

The Fix:

```
$ git remote set-url origin https://github.com/PlayWithMagic/PlayWithMagic.org.git
```

After the fix:

```
$ git remote -v
heroku  https://git.heroku.com/limitless-sands-9772.git (fetch)
heroku  https://git.heroku.com/limitless-sands-9772.git (push)
origin  https://github.com/PlayWithMagic/PlayWithMagic.org.git (fetch)
origin  https://github.com/PlayWithMagic/PlayWithMagic.org.git (push)
```

...noting that both the (fetch) and (push) are updated.  I did a sync w/ my local GitHub client and everything seems fine.

**Comment by marknelsonengineer** [comment]
Question:  Should we add .org to the image files?  Specifically:
- The home page
- The about page
- The top of the help/lexicon page

I think the small icon in the top-left corner of all pages is fine without .org.

I'm neutral on the question, but I wanted to get everyone's thoughts on the subject.

**Comment by davidkneely** [comment]
I believe we should not add .org to the image files.

**Comment by marknelsonengineer** [comment]
As a team, we agreed we don't want to do this.
