### ISSUE TITLE
Clean up Project Home Page

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#143]
Remove unimportant information from the page, and refactor to have a better view towards presentation.

**Comment by pkarjala** [comment]
New page published to http://playwithmagic.github.io/PlayWithMagic.org/ with commit 6b9baec

Unfortunately when doing this through the GitHub interface, there's no way to tag commits.

**Comment by pkarjala** [comment]
Update content and published new page commit c93fd6d.

**Comment by pkarjala** [comment]
At this point I'm looking for a little feedback on this one, as I'd like to keep things simple and move most of the heavy lifting to our GitHub Wiki pages.  Thoughts?

**Comment by davidkneely** [comment]
I like it. It looks lightweight but still performs the functionality we're going after.

**Comment by marknelsonengineer** [comment]
I think we've all looked at it... without objection, I think this is done.
