### ISSUE TITLE
Checkstyle for Magician Sets

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#146]
OK, this is going to be the killer focus of our application.  We'll be gathering feedback on this as we continue to develop on it.

**Comment by pkarjala** [comment]
As per direction from Prof. Johnson, we will be doing a writeup on this portion for the next section of the class.

**Comment by pkarjala** [comment]
Suggest writing this in the Wiki for documentation & design purposes.

Should we put this in a new section of the Developer guide called "Future Releases"?

**Comment by pkarjala** [comment]
Will be calling this feature "Set Notes".

**Comment by pkarjala** [comment]
Current draft at https://github.com/PlayWithMagic/PlayWithMagic.org/wiki/Set-Notes

**Comment by pkarjala** [comment]
First pass on this is complete!

**Comment by marknelsonengineer** [comment]
The documentation is done.  I updated the field labels.  The MVP version of this is done.
