### ISSUE TITLE
Link from README.md to http://playwithmagic.github.io/PlayWithMagic/ is broken.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#150]
I was searching for screenshots to update the User Guide with and found a broken link to "The PlayWithMagic project site" on our README.md. Adding issue to note need for update.

**Comment by pkarjala** [comment]
Thanks, I likely missed this one when updating the GitHub page to reflect the new project name of PlayWithMagic.org.  Will fix.

**Comment by marknelsonengineer** [comment]
Wouldn't it be cool if you could close an issue from the GitHub client?

**Comment by pkarjala** [comment]
You're supposed to be able to by using keywords like "Fixed", but I've never gotten it to work correctly.
