### ISSUE TITLE
Update H1 and H2 headings on Help page to give consistent look and feel.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#152]

**Comment by pkarjala** [comment]
Is this on the Wiki, the Live Site, or elsewhere?

**Comment by marknelsonengineer** [comment]
David,

Can you be more specific as to what you are looking for?  Are they too large, too small?  What are they inconsistent with?  What would you set them to?

Thanks,
Mark

**Comment by davidkneely** [comment]
This issue was posted to highlight the HTML header inconsistencies between the following 2 pages on the live site: 
- http://www.playwithmagic.org/help
- http://www.playwithmagic.org/about
1. The logo and title are huge on the About page.
2. The logo and title are not huge on the Help page.
3. The tagline on the about page is an H1 then goes to H2 and H3 consistently.
4. The "Help" and "Overview" are both H1 and look confusing on mobile.

Please let me know if any of that was unclear.

**Comment by pkarjala** [comment]
Have cleaned this up.  Decided that the help page didn't need to have a header image.  H1, H2, and H3 tags are now more in line with content on the Help page.  I liked the size of H3 on the About page already, so left that as-is.
