### ISSUE TITLE
Add footer to Help page.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#153]

**Comment by marknelsonengineer** [comment]
David... I'm not getting it.  Can you add some more detail as to what you are looking for?  Is it our standard footer or something else?

**Comment by pkarjala** [comment]
Is this for the live site or for the wiki?

**Comment by marknelsonengineer** [comment]
David,

I think I see what you're talking about.  The About and Help pages don't have the same footer as the home page.  

In fact, I think that the footer is _only_ displayed on the home page.  

My 2c worth:  It could go into the Help page if we want.  I don't think it belongs on the About page, which already has all of those links in other places.

**Comment by davidkneely** [comment]
Thanks Mark and Patrick. I will be post more descriptive issues in the future. I was referring to the live site. The footer only appears on the Home page.

**Comment by davidkneely** [comment]
I highlighted the footer issue because I was unable to navigate from the Help page to the About page on the live site.

**Comment by pkarjala** [comment]
Add footer to the Help Page will be the desired location.  We'll leave it off of the About page, as this duplicates the functionality.

**Comment by pkarjala** [comment]
Footer added to Help page, resolved.
