### ISSUE TITLE
Possible Milestone 2 Gaps:  Remove non-functional UI elements

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#156]
- Do we want to remove Search from the home page?  It doesn't work.
- Do we want to remove any/all of the User Login links in the top-right nav?  They don't work intuitively for a naive user yet.

**Comment by davidkneely** [comment]
I understand the rationale behind removing the non-functional UI elements for Milestone 2. However, is there an easier way to simple disable them rather than stripping them from our website?

**Comment by pkarjala** [comment]
Absolutely, we can block out all non-functional HTML elements with a simple  or scala comment blocks.  Hiding them is better than removing them IMHO.

**Comment by pkarjala** [comment]
Resolved.
