### ISSUE TITLE
Support for HTTPS (Buy a certificate)

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#163]
As soon as we get into logins/passwords, we need to secure the site.  This assumes whatever underlying authentication mechanism does not automatically encrypt the passwords (both at rest and in motion).

**Comment by marknelsonengineer** [comment]
The certificate has been:
1. Purchased
2. Installed into Heroku
3. Updated NameCheap to point to new Heroku server

Am waiting for the upstream DNS caches to flush before closing, but it all looks good.

**Comment by pkarjala** [comment]
I believe that we confirmed this is working AOK, propose closing.
