### ISSUE TITLE
Migrate from in-memory database to Postgres

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#165]
We need to carefully migrate to the Postgres setup.

Question:  What do we want the database to be named?

Once named, make sure everyone has it set up on their local machines.

**Comment by marknelsonengineer** [comment]
Hello,

OK, the initial version of the Postgres installation documentation has been written and is here:
[https://github.com/PlayWithMagic/PlayWithMagic.org/wiki/Developer-Guide](https://github.com/PlayWithMagic/PlayWithMagic.org/wiki/Developer-Guide)

I've added the Postgres library to `build.sbt` and updated `application.conf`.  

Finally, I configured each of our four entities to extend `play.db.ebean.model`.  Everything compiles and tests out OK.  The application _requires_ Postgres at this point, but doesn't use it for anything.  A good first step.

I'll be checking the changes in and merging with Milestone-3 shortly.

**Comment by marknelsonengineer** [comment]
We just did the Big Merge.  At this point:
- Magician and MagicianType are in Postgres.  
- Routine, Material and Set are still in-memory.  
- I'll start working on those (and some cleanup) tomorrow.  
- All tests pass.  There are about 10 CheckStyle TODOs in the code.
- There's instructions for configuring the database and the Chrome Driver in the Wiki.

**Comment by pkarjala** [comment]
The majority of the migration work at this point is complete; marking issue resolved.
