### ISSUE TITLE
Implement logical unique constraints on Magician

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#170]
There should be a few 'rules' preventing duplicate Magicians:
- `firstName + " " + lastName`
- `email`
- `stageName`

The rules should be validated in `EditMagicianFormData.validate()` with helpful messages such as:
The Stage Name 'Slydini' has already been taken.

**Comment by pkarjala** [comment]
We can use the @Unique constraint to help with the DB implementation.

**Comment by pkarjala** [comment]
This will be `email` only at this time, as we do not want to prevent people with the same name from creating an account.  We also do not require `stageName` at account creation, so we will need to migrate that to make it a required field in order to consider making it a unique constraint.

**Comment by marknelsonengineer** [comment]
Done
