### ISSUE TITLE
Design Decision:  Routines will be more like Wikis - maintained by the community

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#187]
In Play With Magic, Routines will not be 'owned' by individual users.  Any user can create a routine.  Only administrators can delete a routine.  Someday we should support wiki-like change tracking/control, but that's way down the road.

We have envisioned the notion of Renditions... which is how an individual user performs a routine.  Renditions would be owned by Magicians.

**Comment by pkarjala** [comment]
I think this is a great idea, and one we should move toward for the final release.

**Comment by marknelsonengineer** [comment]
I think we can close this now.  The decision is in the Developer Guide and I've added language about this in the Readme.md file and User Guide.  I reviewed the Project Page and I'm happy with it's content (it's not directly referenced, but it flows into the User Guide nicely.
