### ISSUE TITLE
Set up default images for Profile, Routines, and Materials

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#189]
If a user does not upload an image, we should have one that is filler that shows up in the space where the image should be.

**Comment by pkarjala** [comment]
The best method for doing this would be to simply utilize FontAwesome icons to fill in for blank information.

Suggested icons:

Magician:  http://fortawesome.github.io/Font-Awesome/icon/user/
Routine:  http://fortawesome.github.io/Font-Awesome/icon/magic/
Material:  http://fortawesome.github.io/Font-Awesome/icon/paperclip/ or http://fortawesome.github.io/Font-Awesome/icon/fire/

Alternatively we can use the generic http://fortawesome.github.io/Font-Awesome/icon/picture-o/ for all of them.

**Comment by davidkneely** [comment]
Have implemented placeholders with font-awesome. Icon does not scale with responsive layout. Should we just create images in photoshop with the font awesome icon? Then the image will be responsive and scale with the page. #189

**Comment by pkarjala** [comment]
Let's see how it looks with just the FA Icons and responsiveness.

**Comment by davidkneely** [comment]
Still having issues compiling LESS. Enabled filewatcher but getting error:
`3:24:27 PM An exception occurred while executing watcher 'LESS'. Watcher has been disabled. Fix it.: Invalid executable`

**Comment by pkarjala** [comment]
That's an issue with it not being able to find lessc on your system.

**Comment by pkarjala** [comment]
Taking a closer look, it looks like the `<i>` tags weren't properly being closed with `</i>`, so this is also now fixed.

Have set `font-size: 400px;` for placeholder image.
