### ISSUE TITLE
Style of image name in image.scala.html does not show against grey bg. How do you update the CSS for the file name?

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#194]

**Comment by pkarjala** [comment]
It's likely that the CSS was never written for this, as the page type did not exist at the time.  You can update the LESS file to change the font color property.

Looking at the file at https://github.com/PlayWithMagic/PlayWithMagic.org/blob/imageUploads-1/app/views/bootstrap3/image.scala.html which part is supposed to show the image name?

**Comment by davidkneely** [comment]
This part:

`<input type="file" class="" accept=".jpg, .png, .bmp" name="image">`

**Comment by davidkneely** [comment]
This input group example is exactly how I want it to look: http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/ Working on updating the image.scala.html component to display this way.

**Comment by pkarjala** [comment]
There's a bootstrap portion you may want to look at that covers this:  http://getbootstrap.com/components/#input-groups

**Comment by pkarjala** [comment]
Fixed and working!
