### ISSUE TITLE
Filewatcher not processing updates to style.less on Save.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#197]
Updated style.less with CSS for image upload. Filewatcher is not processing style.less to style.css.
https://www.jetbrains.com/idea/help/transpiling-sass-less-and-scss-to-css.html

`section {
            &#imageUpload {
              color: white;
              background-color: aqua;
            }
          }`

**Comment by pkarjala** [comment]
AOK, I'll get this handled once I'm home.

**Comment by pkarjala** [comment]
Fixed and resolved!  The issue was that the LESS filewatcher tends to turn itself off when you're dropping some of the IntelliJ config files while doing commits.
