### ISSUE TITLE
Images are referred to by their ids instead of a database relation. 

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#209]
- Need to cross reference the magicians and the images together. 
  - Similar to the digits application.
  - OneToOne relationship to update things. 
- Name of the fixImageDbRelations-1
  - Need to update the image relations in the database.

**Comment by pkarjala** [comment]
See Issue #207.

**Comment by davidkneely** [comment]
Fixed. #209
