### ISSUE TITLE
Do not allow unregistered users to edit or delete Routines / Sets

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#212]
Currently they can, and this wipes the database!

**Comment by marknelsonengineer** [comment]
Patrick... I agree with the theory we discussed after class today.  It was a good demonstration of why this feature is important.

**Comment by pkarjala** [comment]
I'm going to plan on baking this in over the next few days, such that users can only Create and Delete their own content for Routines and Materials (for now), and can only CRUD their own Profiles and Sets

**Comment by marknelsonengineer** [comment]
Patrick,

What if we remove the ability for any user (even the creator) to remove the routine?  Make it an administrative-only function.  

Mark

**Comment by pkarjala** [comment]
I agree that this would be a good idea.  We should map out an "administrative backend" for admins to functionally interact with the site.

**Comment by pkarjala** [comment]
See also #217.

**Comment by pkarjala** [comment]
This issue is resolved with Commit f840ee9

**Comment by pkarjala** [comment]
Unauthorized / non-logged in viewers can no longer Delete or Edit Routines, and can no longer access Sets in any form.  Resolved.
