### ISSUE TITLE
Review Johnson's feedback on Milestone 3

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#215]
- Probably not good for unlogged-in users to edit/delete all content. 
- Maybe only allow "creator" of content to be able to delete it? :)
- Implement first pass at Magic Checkstyle.

**Comment by pkarjala** [comment]
Excellent feedback and awesome work on our project guys.  We've parsed out all commitments for the next sprint, closing this issue.
