### ISSUE TITLE
Decide upon access rules for logged in users

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#217]
What should users be able to do?

**Comment by pkarjala** [comment]
We propose:

# Unauthenticated
- Browse Routines
- Log In
- Sign Up

# Authenticated
- Browse Routines
- Browse Sets
- Browse Magicians
- Create Routines
- Create Sets
- Edit Any Routines
- Edit OWN Sets
- Edit own Profile
- Run Set Notes
- Log Out

**Comment by pkarjala** [comment]
Do we want to allow Authenticated Users to delete their own sets?

**Comment by pkarjala** [comment]
Unauthenticated portion is complete.

**Comment by marknelsonengineer** [comment]
Patrick,

Yes, I think that’s OK.

Mark

**Comment by pkarjala** [comment]
This has been baked into the current Master release, and is resolved.
