### ISSUE TITLE
Fails tests in Milestone-4.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#223]
1. tests.TestStaticContent
2. tests.TestRoutineCRUD
3. tests.TestMaterialCRUD
4. tests.TestMagicianCRUD

**Comment by davidkneely** [comment]
Fixed tests.TestStaticContent. #223

**Comment by davidkneely** [comment]
Fixed tests.TestRoutineCRUD. #223

**Comment by davidkneely** [comment]
Fixed tests.TestMagicianCRUD. #223

**Comment by pkarjala** [comment]
Should be all fixed as of bab389d.
