### ISSUE TITLE
Footer does not scroll with lots of content on a page.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#25]
After I added more content to the displayEffect.html page the footer stays in the middle of the page and does not scroll to the bottom. Do we want to have it fixed at the bottom of the screen at all times? Even on mobile?

**Comment by pkarjala** [comment]
I'm already aware of this and have a fix in the works!

**Comment by pkarjala** [comment]
Fixed in Commit 0d412b8.
