### ISSUE TITLE
We need a logo.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#27]

**Comment by pkarjala** [comment]
Do we want to go with something more modern?  Simple?  Complex?  Should it incorporate "magic" effects?

**Comment by marknelsonengineer** [comment]
How large of a logo are you thinking?

**Comment by davidkneely** [comment]
I'd prefer to go with something moder. I like the idea of the logo looking like a magic spell book. Our logo should be simple enough to read well from far away. And it should look good as an icon on the iPhone home screen.

**Comment by pkarjala** [comment]
I will ask my co-worker Michelle, who is a graphic designer, if she is willing to do any mockup logo work for us.

**Comment by pkarjala** [comment]
Should be a vector image, square, non-transparent background.

**Comment by pkarjala** [comment]
Have asked my co-worker and her turnaround would be 2 weeks for a logo design incorporating a book with a "magic" feel to it.  Logo would be flat, no color, transparent and non-transparent background versions.

**Comment by marknelsonengineer** [comment]
If she can do it, that would be great.  Is there anything we can do for her?

**Comment by pkarjala** [comment]
Proposal written and sent to artist.

**Comment by pkarjala** [comment]
After the return quote, we've decided to go with something else.  I should have a logo mocked up tonight.

**Comment by pkarjala** [comment]
Here's the logo that I've mocked up.
![logo_original](https://cloud.githubusercontent.com/assets/5232936/6989734/6e404532-d9fb-11e4-8e82-c4727e06bea0.png)

**Comment by pkarjala** [comment]
Logo has been added to main page, closing.
