### ISSUE TITLE
Get social media glyph icons to show in line and in a bigger font. I can't figure out how to target and affect them with LESS.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#29]

**Comment by pkarjala** [comment]
Font Awesome icons can be manipulated via direct in-line classes, similar to Bootstrap layouts.  See http://fortawesome.github.io/Font-Awesome/examples/

**Comment by davidkneely** [comment]
Fixed social media glyph icons to show in line and in a bigger font. #11
