### ISSUE TITLE
Add search bar to navigation.

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#31]
Should be in-line, use integrated input buttons:  http://getbootstrap.com/components/#input-groups-buttons and FontAwesome for the search.

Can likely copy from main body search on home page.

**Comment by pkarjala** [comment]
Added with Commit e7c97ce

**Comment by pkarjala** [comment]
Need to copy over to other pages; will not display in nav bar on home page.

**Comment by davidkneely** [comment]
Browse Effects and Browse Sets navigation items are looking good! #31

**Comment by pkarjala** [comment]
This is pretty much complete!
