### ISSUE TITLE
Create in-memory database for testing purposes.

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#48]
Should be able to store Users and Routines.

**Comment by pkarjala** [comment]
Both MagicianDB and ContactDB objects have been created.

**Comment by pkarjala** [comment]
Mark has updated with RoutineDB.

**Comment by marknelsonengineer** [comment]
Routine & Magician in-memory CRUD models are done.  I'd say the essence of this issue is complete.
