### ISSUE TITLE
Born Standing Up, Steve Martin

### ISSUE THREAD

**Issue by philipmjohnson** [PlayWithMagic/PlayWithMagic.org#50]
Just finished reading this and thought of your app. Steve Martin's early act involved a lot of magic and he talks a lot about the process of finding/inventing material and forming an act from it.

http://www.amazon.com/Born-Standing-Up-Comics-Life/dp/1416553657

You might not get actual requirements out of reading it, but it will be interesting.

**Comment by davidkneely** [comment]
I read BSU. I can comment on it during our meeting.

**Comment by marknelsonengineer** [comment]
That reminds me of a 2002 movie, Comedian, a documentary following Jerry Seinfeld while he is rebuilding his act from scratch over a year.

There's also a contemporary movie called The Magic Life about three unknown magicians trying to refactor their act in the hopes of making a living as full-time professional magicians.

From the feedback we are getting, there is definitely a demand for this sort of thing.
