### ISSUE TITLE
Scalability not an important requirement

### ISSUE THREAD

**Issue by philipmjohnson** [PlayWithMagic/PlayWithMagic.org#52]
I notice from the README that there is a concern in the team regarding the "production" quality of the Play web server.  First, since Play is used by (for example) LinkedIn, it can certainly scale.

But the more important thing to note is that this is a "boutique" application: it will appeal to a total user population in the thousands or 10's of thousands, and their use will be quite intermittent. You're not building a Twitter.   

The limited user base is not a negative feature: in fact, it means you have the potential to "dominate" if you create something with high content quality. Go for it!

**Comment by pkarjala** [comment]
Duly noted and we'll push forward to create something amazing for our userbase.
