### ISSUE TITLE
Don't get hung up on drag and drop

### ISSUE THREAD

**Issue by philipmjohnson** [PlayWithMagic/PlayWithMagic.org#53]
The readme discusses various drag-n-drop UI capabilities. If you can implement these "cheaply", then by all means go ahead. 

But the primary thing that will sell users on this system is the quality of content, not the sexiness of the UI.  So focus on the former, not the latter.

**Comment by pkarjala** [comment]
Completely agree; we were bandying around with this idea to give the application some flair, but if it gets in the way of the user experience, there's no point.  We'll move back to a simpler more user-friendly implementation unless time allows for us to create something amazing.
