### ISSUE TITLE
Make addition of quality content an explicit part of each milestone

### ISSUE THREAD

**Issue by philipmjohnson** [PlayWithMagic/PlayWithMagic.org#54]
For your user community to be able to adequately assess your system (or even use it in a realistic fashion), it has to be seeded with a significant amount of high quality content (i.e. routines and sets).  

Please make the addition of specific routines and sets an explicit part of each milestone.  The content has to be "real", in the sense that it is of acceptable quality for a real end-user of the system.

**Comment by marknelsonengineer** [comment]
Yes, we're on it.  We've already discussed seeding the in-memory database with some content.  I will be asking our 'Consulting Magicians' to add content as well.  We will be sure to specifically add this to all of our milestones.
