### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by philipmjohnson** [PlayWithMagic/PlayWithMagic.org#55]
README is in a bad state. There is redundant content.  Please clean up.

**Comment by pkarjala** [comment]
Thanks for the heads up, we'll get this cleaned up.  This likely happened in with the merge conflict in a3dfa3d.

**Comment by pkarjala** [comment]
This looks fixed as of commit 95c655b?

**Comment by marknelsonengineer** [comment]
Done & tested.
