### ISSUE TITLE
Problems with local checkstyle references across multiple computers

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#56]
Currently, a local checkstyle.xml file reference on my machine will cause issues when the repo is cloned to someone else's machine, where the checkstyle file is not in the same location.  Need to host the checkstyle file online, or refer to an online version, that can be easily set globally for the entire project.

**Comment by marknelsonengineer** [comment]
Here's Dr. Johnson's URL
http://philipmjohnson.github.io/ics613s15/morea/coding-standards/checkstyle.xml

**Comment by pkarjala** [comment]
David will push the revised config copy up to GitHub.

**Comment by davidkneely** [comment]
Done. #56
