### ISSUE TITLE
Transition project over to a GitHub Organization

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#57]
Should be hosted by a GitHub Organization instead of an individual account.

**Comment by pkarjala** [comment]
See https://help.github.com/articles/creating-a-new-organization-account/

**Comment by marknelsonengineer** [comment]
...when this is done, please give me ownership of the task (or I'll create new tasks) to:
1.  Look into a group eMail for the project hosted by GitHub.
2.  Workup a Product Home Page

**Comment by pkarjala** [comment]
See https://help.github.com/articles/transferring-a-repository/ for specific instructions on transfer after organization is created..

**Comment by pkarjala** [comment]
New organization created at https://github.com/PlayWithMagic

**Comment by pkarjala** [comment]
Transfer of repo is complete.  Please update your git repo settings to point to the new location:

```
$ git remote set-url origin https://github.com/PlayWithMagic/PlayWithMagic.git
```

**Comment by marknelsonengineer** [comment]
ALSO:  In the GitHub client, go to File > Reload Repositories.
