### ISSUE TITLE
Patrick:  Do you want to change your eMail on the Wiki/Contact Us page...

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#58]
... from your hawaii.edu to the gmail.com account. 

Also, I checked the gmail account my calendar program is using to send invites your way... it's just what you wrote down.  You should have received 3x invites by now.  Let me know if you didn't get `em.

**Comment by pkarjala** [comment]
Have updated email on the wiki page, now set to gmail.com.

Still not receiving calendar invites, no clue why.  Try sending a direct email?

**Comment by marknelsonengineer** [comment]
Sent a direct eMail and 2x calendar invites (one to each account).  The calendar invites do not show up in my outbound mailbox.

**Comment by pkarjala** [comment]
Direct email received no issues.

**Comment by pkarjala** [comment]
Finally got the calendar invites to my hawaii.edu account, still haven't received them to my gmail.com account.

I'm not going to worry about it; we usually are good about checking in on meetings as they come up.
