### ISSUE TITLE
Register a domain name

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#61]
Dr. Johnson just posted some guidance on what he’s looking at for the first milestone.  One element will be a live domain name.  He suggested we purchase a cheap name from NameCheap.com for $11.  

I found PlayWithMagic.org for $12.

Another alternative is the new gTLDs.  I purchased ‘nelson.engineer' last year when .engineer came out.  Unfortunately, there’s no .magic gTLD.  Here’s the current list:

http://newgtlds.icann.org/en/program-status/delegated-strings

...I recommend we register with PlayWithMagic.org.

**Comment by pkarjala** [comment]
I think that PlayWithMagic.org is a great fit.  At $4 each, I'm totally down for it.

I did a quick scan over the gTLDs, and .HERE might be fun as:  playwithmagic.here

.GUIDE also kind of works:  playwithmagic.guide

.ROCKS:  playwithmagic.rocks

Regardless, I think we should stick with the .org for now.

**Comment by davidkneely** [comment]
Same here. I agree that we should go with .org.

**Comment by marknelsonengineer** [comment]
Done.  It's currently pointing to my Raspberry Pi server.  I'll need to do a little work to get it to resolve correctly.

**Comment by pkarjala** [comment]
FYI, I have purchased playwithmagic.space as part of our class assignment.
