### ISSUE TITLE
Determine if we will be using Javascript in our PlayWithMagic application.

### ISSUE THREAD

**Issue by davidkneely** [PlayWithMagic/PlayWithMagic.org#64]
If we are planning to use Javascript in PlayWithMagic, I'd like to discuss it on Monday. If we are using Javascript we should all adhere to consistently writing our tests with PhantomJS or HTMLUNIT across the application. The reason I bring this up is because we are no longer implementing drag and drop functionality. What else would we need Javascript for? Let's discuss on Monday.

**Comment by pkarjala** [comment]
I don't think we'll be using any heavy JavaScript beyond what Bootstrap already utilizes, but we can def. discuss further on Monday.

**Comment by pkarjala** [comment]
We are agreed we will focus on HTMLUNIT for tests.
