### ISSUE TITLE
How do we want to associate Magicians --> Routines?

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#65]
Wondering how we want to associate a Routine with a Magician, or vice-versa?  I think it's cleanest to include the user ID for a Magician in the Routine that they create; this way we don't have to worry about a huge growing list of Routines being stored with a Magician.

Thoughts?

**Comment by marknelsonengineer** [comment]
Patrick,

I’ll put together a draft Enterprise-Relationship Diagram this evening and present it tomorrow.

Mark

**Comment by marknelsonengineer** [comment]
Patrick,

I took this question and ran with it.  I built up a proposed Entity-Relationship diagram — we can review it at our next meeting.  Here’s my thinking:  For new, we maintain an ER diagram that generally matches our phony in-memory data model.  The in-memory data model gets built from the concepts articulated in the ER Diagram, but we only build what we immediately need.  In other words, the ER diagram is the blueprint for the long-term model.

A picture of the model and my notes are in the Wiki here:  https://github.com/PlayWithMagic/PlayWithMagic/wiki/Datamodel https://github.com/PlayWithMagic/PlayWithMagic/wiki/Datamodel

There’s a new folder called ‘database’ that has the DDL SQL and the image.

In answer to your specific question, I agree with your approach.  Adding detail, I’d propose that we have a unique ID for magician called ‘magician.magician_UID’.  In the Routine table, we have a foreign key called ‘routine.magician_UID’.

I know Johnson doesn’t want us to build the database up-front (I agree with that), but I think it’s a good idea to design the data model (as much as possible) up-front and build it out as we need it.

Mark

**Comment by davidkneely** [comment]
> In answer to your specific question, I agree with your approach. Adding detail, I’d propose that we have a unique ID for magician called ‘magician.magician_UID’. In the Routine table, we have a foreign key called ‘routine.magician_UID’.

I agree that we should use the primary key of magician as a foreign key for each routine. The data model looks great. Looking forward to reviewing it today during our meeting.

**Comment by pkarjala** [comment]
This will be contingent upon the user authentication portion being complete.

**Comment by pkarjala** [comment]
I believe this has been built at this point; @marknelsonengineer can you comment?

**Comment by pkarjala** [comment]
Discussing with @marknelsonengineer , we are agreed that this issue is addressed and resolved.
