### ISSUE TITLE
Point domain name to hosted server

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#67]

**Comment by marknelsonengineer** [comment]
The IP address is live and has propagated.  This verifies the DNS infrastructure and the fact that we have control over the domain.

**Comment by pkarjala** [comment]
Awesome; shall we keep this issue open for tracking changes?

**Comment by marknelsonengineer** [comment]
Yes, let’s keep it open until we’ve deployed to Heroku and pointed the domain there.

**Comment by marknelsonengineer** [comment]
Folks, it's time to do the merge with master.  This evening, I did the `heroku create` command on the PlayWithMagic repo.  No problems.  

Next, I did a `git push heroku Milestone-1` command.  Parts of it deployed, however, Heroku kicked out an error message:  `remote: Pushed to non-master branch, skipping build.`

...and it did not fully deploy.

So, we need to merge with master and then do the deployment.

**Comment by pkarjala** [comment]
Master merge performed with Mark as of commit 5c48a43.

Mark deployed to Heroku, application is live at http://limitless-sands-9772.herokuapp.com/

**Comment by pkarjala** [comment]
DNS record updated to point http://www.playwithmagic.org/ to http://limitless-sands-9772.herokuapp.com/.  Heroku updated to recognize www.playwithmagic.org domain.

**Comment by pkarjala** [comment]
Done and done.

**Comment by marknelsonengineer** [comment]
In the spirit of test early and often, I've merged Milestone-1 with master and redeployed our latest work to Hiroku.
