### ISSUE TITLE
Video of Routine

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#68]
We would need to worry about

-- Video isn't spam
-- Video is of routine
-- Video is not inappropriate (though YouTube will take care of this for us)
-- Reporting posted videos
-- How do we handle multiple videos?
-- Voting on quality of video?

**Comment by marknelsonengineer** [comment]
Allow users to contribute their own performances of this routine. 

Usecase:  Any user should be able to post links to YouTube of them doing their version of the Routine.

External links to clips that show the routine, or embedding a video.

Allow other users to rate the performances.

**Comment by marknelsonengineer** [comment]
Without objection, I'd like to turn over this issue to Patrick to implement the player.

**Comment by pkarjala** [comment]
Everything you'd ever want to know about embedding YouTube videos:  https://developers.google.com/youtube/player_parameters

**Comment by pkarjala** [comment]
Embedded player implemented, closing!
