### ISSUE TITLE
Play imports are randomly not working

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#70]
Occasionally when opening up the project files, the Play imports are not working, and it will cause issues in IntelliJ.  Investigate and fix.

**Comment by pkarjala** [comment]
So, here's the root issue of this.

The problem is that when I originally set up the Play Framework in our existing project, I didn't remake the project as a Play project.  Instead, I refactored our Mockup by dumping the Play files into it.  As a result, IntelliJ still viewed it as an HTML Web project...but for some reason would still let it run.  Today that caught up with this.

The resolution is that I re-made a brand new Play project from scratch using `activator new` from the command line.

Next I merged all of our in-progress branches back into Mockup-1 so that all working files that might be touched by this were merged back into a single branch.

After this, I brought up the "dirty" copy of PlayWithMagic from Mockup-1, and then copied over ONLY the required project files, such as app/controllers, app/models, app/views, conf, doc/images, mockup, and so forth.  I did not modify any other files in the freshly created Play project.  I also made sure that checkstyle was properly configured to use our online copy.

Once this was done, I ran checkestyle and did an `activator run` and verified that the project ran correctly.

After verifying everything worked, I created a new branch off of Mockup-1 called "Fix-Play-Framework", and merged all of the changes I'd made in the temporary new Play project into the git directory.  This was then committed, and merged back into Mockup-1, so that our main Mockup-1 branch is clean.

At this point, everything /should/ be fixed.  The project is built from a fresh Play framewok.  I'd like you both to pull the changes and test them on your local system.

Also, after some further futzing around, we should also probably run `activator clean` after each pull and before doing `activator run`, as this cleans out some old crud from activator's association with the project.

**Comment by marknelsonengineer** [comment]
Patrick,

Thank you for all of your hard work on that.  I had a glimpse as to what you must have slogged through during that work period class — thanks!

I blew away the PlayWithMagic directory on my Mac and re-cloned from GitHub.  After the initial import, the following files had changes:
.idea/misc.xml
.idea/modules/root-build.iml
.idea/modules/root.iml

We should discuss how to handle these types of local files and how we treat them at checkin.

Checkstyle passed.  Activator run works.  Activator test fails some tests.

I’ll work on some cleanup activities (removing Digits elements) and try to improve the foundation.

Mark

**Comment by pkarjala** [comment]
I think the solution is ultimately to run `activator clean` when porting between different systems to make sure there's no residual build data from previous builds on a different branch.

I hadn't done any work on Activator test yet, so no worries there.

Marking complete.
