### ISSUE TITLE
Routine Material List

### ISSUE THREAD

**Issue by marknelsonengineer** [PlayWithMagic/PlayWithMagic.org#83]
Materials Multi-Object List Control

Item - Single line text
Inspectable - Yes/no flag
Given away - Yes/no flag
Consumed - Yes/no flag
Price - Amount + Currency
Where to find it - URL
Notes - Multi line text
Picture - Image

Help:  Is the item a regional item?  Is it difficult to procure?  How well does it hold up over time?

**Comment by pkarjala** [comment]
Just the modeling portion, at least.

**Comment by marknelsonengineer** [comment]
The Merge is complete.  It passes JUnit tests, but I've trashed CheckStyle for awhile -- I'll get it fixed in the next day.

**Comment by marknelsonengineer** [comment]
Done.  Outstanding items are in the Issues list.
