### ISSUE TITLE
Need to generate an About page

### ISSUE THREAD

**Issue by pkarjala** [PlayWithMagic/PlayWithMagic.org#97]
Should host things such as information about the website, help information, links to GitHub, etc.

Essentially the information in the Footer.

**Comment by pkarjala** [comment]
Will also host all necessary graphic attributions, Thank Yous, etc.

**Comment by marknelsonengineer** [comment]
Create an About page.  Include the names of the authors and highlight the consulting magicians.

The purpose of this app is to:
Find new magic tricks
Keep track of the tricks you do, like, etc.
A personal catalog of the tricks you’ve developed

Attempt to use game theory (rewards) to encourage magicians to contribute routines and participate in the community.

Share as much as you want, but don’t put anything in here you wouldn’t want others to see.  Even if we had sharing controls (which we don’t yet), we can’t guarantee the site won’t get hacked and all of the information gets dumped to the Internet.

**Comment by pkarjala** [comment]
Initial setup and creation done; will likely need a second pass on content.

**Comment by marknelsonengineer** [comment]
Looks good.  Closing.
